version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo [Syncing DAG Files]
      - aws --version
      - aws s3 sync ./dags s3://ptbwa-mwaa/dags
  post_build:
    commands:
      - echo [Syncing DAG Files Completed]
